import type { ReactNode } from "@/configs/imports-wrapper";
import type { Metadata } from "next";
import { inter } from "./fonts";
import "./global.css";
import NextTopLoader from "nextjs-toploader";
import Header from "@/components/organisms/nav/header";
import Footer from "@/components/organisms/footer";
import EmailSubscribe from "@/components/organisms/email-subscribe";
import BottomNav from "@/components/organisms/nav/bottom";
import ToastContext from "@/context/toast";
import FirebaseUserContext from "@/context/firebase-user";
import CartProvider from "@/context/cart";

export const metadata: Metadata = {
  title: "CHAWKBAZAR CLONE",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
  dialog
}: Readonly<{
  children: ReactNode;
  dialog: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader color="rgb(90, 90, 90)" height={1.5} />
        <FirebaseUserContext>
          <CartProvider>
            <ToastContext>
              {dialog}
              <Header />
              <main>{children}</main>
            </ToastContext>
            <BottomNav />
          </CartProvider>
        </FirebaseUserContext>
        <div className="wrapper1920 mx-auto">
          <EmailSubscribe />
        </div>
        <Footer />
      </body>
    </html>
  );
}
