import type { Metadata } from "next";
import { inter } from "../fonts";
import "./globals.css";

import Header from "@/components/main-header";
import EmailSubscribe from "@/components/email-subscribe";
import Footer from "@/components/footer";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app"
};

export default function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <Header />
            <main>{children}</main>
            <EmailSubscribe />
            <Footer />
         </body>
      </html>
   );
}
